# Generated by Django 3.0.6 on 2020-05-31 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200530_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Customer',
        ),
        migrations.AddField(
            model_name='order',
            name='Customers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
